### ISSUE TITLE
[GraphQL Endpoint Language]: Lists with non null elements (`[String!]`)is not recognized

### ISSUE THREAD

**Issue by programaths** [JetBrains/js-graphql-intellij-plugin#202]
## Version and Environment Details

<details>
   <summary>Env details</summary>
  <pre>
IntelliJ IDEA 2018.3.2 (Ultimate Edition)
Build #IU-183.4886.37, built on December 17, 2018
Licensed to ***redacted***
You have a perpetual fallback license for this version
Subscription is active until December 13, 2019
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
</pre>
</details>

__Operation system__: WIN 10

__IDE name and version__: IntelliJ IDEA 2018.3.2 (Ultimate Edition)

__Plugin version__: 1.7.2

## Expected Behaviour

Parser recognize lists with non null elements

## Actual Behaviour

Parser does not recognize lists with non null elements

## Steps to Reproduce / Link to Repo with Reproduction and Instructions

create a "foo.graphqle" file with this content :
```
type TestList {
    list:[String!]
}
```

The first exclamation mark will be underlined in red. (unexpected element)

**Comment by jimkyndemeyer** [comment]
HI Christian.

Thanks for using the plugin.

The "GraphQL Endpoint Language" is a variation of GraphQL SDL, so there isn't a 1:1 syntactic mapping.

The main differences are:
- Directives are placed before types and fields, similar to Java annotations
- Types implementing interfaces don't need to re-declare the fields from the interfaces
- Imports are natively supported

The story behind the language is that we needed these features in the product team that I lead to build our endpoint.

Regarding your issue, we never needed to declare non-null in our lists, so to keep the implementation simple it's currently not supported.

If you're using the plugin to help with completion/error highlighting you could take a look at the v2 alpha of the plugin which provides these features for GraphQL SDL: https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases/tag/2.0.0-alpha-3

Best regards,
Jim.
