### ISSUE TITLE
Fragments work in .ts files but not .vue

### ISSUE THREAD

**Issue by NicholasFeldman** [JetBrains/js-graphql-intellij-plugin#215]
## Version and Environment Details
__Operation system__: MacOS Mojave 10.14.3

__IDE name and version__:  PHPStorm 2018.3

__Plugin version__: v2.0.0-alpha-5

## Expected Behaviour
GraphQL fragments in a both a TypeScript and a Vue file will have proper schema hinting and validation
## Actual Behaviour
GraphQL fragments with identical queries don't recognize the field of the query in a Vue file. Files are side by side in the same directory.

## Steps to Reproduce / Link to Repo with Reproduction and Instructions
Images included.
<img width="471" alt="screen shot 2019-02-21 at 1 49 22 pm" src="https://user-images.githubusercontent.com/1383438/53193791-e5bf2800-35df-11e9-9ad2-ddc72f7359ca.png">
<img width="400" alt="screen shot 2019-02-21 at 1 49 32 pm" src="https://user-images.githubusercontent.com/1383438/53193793-e6f05500-35df-11e9-8d96-a430c8d1a92c.png">

**Comment by koresar** [comment]
I'm using .vue files too. However, everything is just fine.

I had similar issue when there was no scope configured in the IDE or when I had two different scopes. You might have the issue because your scope doesn't include .vue files.

Currently I have single scope with includes everything: `file[project-name]:*/`

**Comment by NicholasFeldman** [comment]
I have a single project scope like that that does include vue files, but after reindexing it still doesn't work. Here's what I have in my `.graphqlconfig` as well:

```json
{
    "endpoints" : [
        {
            "name": "Development",
            "url": "http://localhost:8081/api/graphql",
            "options" : {
                "headers": {
                    "user-agent" : "JS GraphQL"
                }
            }
        }
    ],
    "excludes": [
        "./backend/vendor/**"
    ]
}
```

**Comment by gunta** [comment]
+1

**Comment by bassneck** [comment]
I'm having this problem as well ☹️
Fragments defined in .graphql and .ts are correctly highlighted and are available in autocompletion; but fragments defined in .vue files are not discoverable.
<img width="317" alt="Screen Shot 2020-11-18 at 12 07 31 PM" src="https://user-images.githubusercontent.com/505411/99461471-c4e35c80-2996-11eb-9682-a427d373e031.png">
<img width="296" alt="Screen Shot 2020-11-18 at 12 07 37 PM" src="https://user-images.githubusercontent.com/505411/99461483-c876e380-2996-11eb-8b1f-cd37a5cfb4d4.png">

```
.graphqlconfig
{
  "name": "GraphQL Schema",
  "schemaPath": "schema.graphql",
  "includes": ["*.graphql", "*.vue", "*.ts", "*.js"],
  "excludes": ["node_modules/**"]
}
```
(I have just switched to graphql-codegen and use it for schema introspection now; however, adding endpoint config back had no effect)

**Comment by AAllport** [comment]
Seems to still be an issue with V3 (PHPStorm 2021.2.2)
We've got a Larvel [Lighthouse](https://lighthouse-php.com/) + [vue-apollo](https://apollo.vuejs.org/) project with a split configuration:
```json
{
  "name": "App Graphql Schema",
  "projects": {
    "server": {
      "includes": [
        "graphql/*.graphql",
        "schema-directives.graphql"
      ]
    },
    "client": {
      "schemaPath": "_schema.graphql",
      "excludes": [
        "graphql/*.graphql",
        "schema-directives.graphql"
      ],
      "extensions": {
        "endpoints": {
          "Local GraphQL Endpoint": {
            "url": "http://localhost/graphql",
            "headers": {
              "user-agent": "JS GraphQL"
            },
            "introspect": true
          }
        }
      }
    }
  }
}
```

Creating a fragment:
```js
const TodoListItemData = gql`fragment TodoListItemData on ToDoItem{
    id, name, details, position, status
    todoable {... on Project { id, name }}
}`;
```

Usage:
![image](https://user-images.githubusercontent.com/3750120/135616108-5f8b4d8c-ef01-4886-aa07-23c53c8169c4.png)


No errors at runtime
