### ISSUE TITLE
Connect via proxy

### ISSUE THREAD

**Issue by ruudk** [JetBrains/js-graphql-intellij-plugin#228]
## Version and Environment Details
PhpStorm 2019.1
Build #PS-191.6183.55, built on March 20, 2019
Licensed to TicketSwap BV / Ruud Kamphuis
Subscription is active until August 25, 2019
JRE: 1.8.0_202-release-1483-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.3

Is it possible to specify a proxy to use? 

For example, in order to access my API, I need to do a curl request like this:
```
http_proxy=localhost:7080 HTTPS_PROXY=localhost:7080 curl https://my.api/graphql
```

I tried the following:
```json
{
  "schema": {
    "request": {
      "url": "https://my.api/graphql",
      "method": "POST",
      "postIntrospectionQuery": true,
      "options": {
        "headers": {
          "user-agent": "JS GraphQL"
        },
        "proxy": "localhost:7080"
      }
    }
  },
  "endpoints": [
    {
      "name":  "My Api",
      "url": "https://my.api/graphql",
      "options": {
        "headers": {
          "user-agent": "JS GraphQL"
        },
        "proxy": "localhost:7080"
      }
    }
  ]
}
```

**Comment by tsareg** [comment]
I'd really like to see this feature implemented. Though in my case I need quite opposite run without any proxy, basically setting `HTTPS_PROXY='' HTTP_PROXY=''`. Maybe there is some other way to do that in IDEA?

**Comment by deejay1** [comment]
For a workaround you can try something like this in `.graphqlconfig`:

```json
{
  "name": " GraphQL Schema",
  "schemaPath": "schema.graphql",
  "extensions": {
    "endpoints": {
      "GraphQL Endpoint": {
        "url": "http://my_proxy_address/graphql",
        "headers": {
            "host": "my_destination_host",
          "user-agent": "JS GraphQL"
        },
        "introspect": false
      }
    }
  }

**Comment by vepanimas** [comment]
GraphQL requests should respect bulit-in IntelliJ proxy settings since 3.2.0.
