### ISSUE TITLE
When schema.json size is greater than idea.max.intellisense.filesize, inspections break

### ISSUE THREAD

**Issue by nhusher** [JetBrains/js-graphql-intellij-plugin#265]
I'm having an issue loading a very large 2.7mb GraphQL schema.json file. The service appears to parse and load the definitions correctly, but the inspector doesn't seem to have access to the types.

I've pared down the schema file, and it appears that when I cut it down to below the default 2.5mb limit, the inspector suddenly can validate queries against the schema.

I don't know if there's a way to work around that, so that the inspector is still available even if the schema file size is very large.

## Version and Environment Details
__Operation system__: OS X 10.14.5

__IDE name and version__: IntelliJ Idea Ultimate 2019.1.3

__Plugin version__: v2.2.0

## Expected Behaviour

Schema files of arbitrary size (up to some reasonable limit—is 2.7mb unreasonable?) should continue to work with the inspector.

## Actual Behaviour

Large schema.json files do not work with the inspector.

## Steps to Reproduce

1. Create a pretty big schema and record its file size in kilobytes
2. Create a query in a JS file that makes use of the schema
3. In IntelliJ, go to Help -> Edit Custom Properties
4. In the properties file it opens, set `idea.max.intellisense.filesize={less than filesize from step #1}` 
5. Restart IntelliJ
6. Notice that inspections are now broken for that query

## Workaround

Set `idea.max.instellisense.filesize` to a number greater than the schema file.

**Comment by nhusher** [comment]
I may have an example schema.json, but I need to find out if I can share it or if it's proprietary.

**Comment by jimkyndemeyer** [comment]
Hi Nicholas.

Thanks for using the plugin.

The JSON format is supported mostly for backwards compatibility with v1 of the plugin.

I recommended that you set your `schemaPath` to a file name with a `.graphql` extension such that the plugin converts the introspection JSON data to GraphQL SDL when you run the introspection query.

See https://jimkyndemeyer.github.io/js-graphql-intellij-plugin/docs/developer-guide#working-with-graphql-endpoints-and-scratch-files for the relevant introspection steps.

It should perform a lot better, and the file size is often reduced by a factor of 10 or more.

Hope that addresses your issue.

Best regards,
Jim.

**Comment by nhusher** [comment]
Thanks for that context, I wasn't aware that `schema.json` wasn't well-supported. I'm just joining this project and don't have a good sense of how difficult it will be to convert to using a graphql file instead, since it seems like there's a bunch of tooling around using this json file.

Should I open a PR on the docs that mentions that `schema.json` isn't preferred?

**Comment by euvs** [comment]
Hi Jim,

Just my 2c. I'm experiencing the same problem with `.graphql` file. The file is 2.7Mb at the moment and the inspector broke. The workaround suggested by Nicholas helps. 
I set `idea.max.intellisense.filesize=3500`. It works for now.

**Comment by nhusher** [comment]
Just to close a loop here: the reason the company I work for is using `schema.json` files instead of GraphQL schema files is that's what Apollo's command line tooling produces when you download a remote schema locally. They don't appear to support a non-JSON variant, as far as I can tell, though I may be missing something.

**Comment by jimkyndemeyer** [comment]
@nhusher have you tried simply using a `.graphql` file extension with the tool. I'd be surprised if they don't support this.

**Comment by nhusher** [comment]
They do not. Here's the code that powers `apollo client:download-schema`:

```ts
const schema = await project.resolveSchema({ tag: flags.tag });
writeFileSync(
  args.output,
  JSON.stringify(introspectionFromSchema(schema), null, 2)
);
```
[source](https://github.com/apollographql/apollo-tooling/blob/master/packages/apollo/src/commands/client/download-schema.ts)
