### ISSUE TITLE
Fields are not found for a default value of an input

### ISSUE THREAD

**Issue by Enrico2** [JetBrains/js-graphql-intellij-plugin#310]
## Steps to Reproduce

```graphql
input Input {
	foo: Boolean = true
}

type SomeType {
	fieldWithArgs(arg: Input = { foo: true }): String
}
```

![image](https://user-images.githubusercontent.com/161314/72188527-67ae7000-33af-11ea-9b69-156be96f0a79.png)

## Version and Environment Details
__Operation system__: MacOS

__IDE name and version__: IntelliJ IDEA 2019.3.1 (Ultimate Edition)
Build #IU-193.5662.53, built on December 17, 2019
Subscription is active until April 17, 2020
Runtime version: 11.0.5+10-b520.17 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.2
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: 
Non-Bundled Plugins: Lombook Plugin, PlantUML integration, com.intellij.kubernetes, com.intellij.lang.jsgraphql, com.thoughtworks.gauge, intellij.prettierJS, io.ktor.intellij.plugin, io.protostuff.protostuff-jetbrains-plugin, org.intellij.plugins.hcl, org.intellij.scala, org.jetbrains.kotlin, org.jetbrains.plugins.hocon, org.plugin.dot.id, org.sylfra.idea.plugins.linessorter

__Plugin version__: 2.3.0

## Expected Behaviour

No red

## Actual Behaviour

red, unknown field

**Comment by Tantatorn-dev** [comment]
I've found this error too, even though my version is 4.0.2

**Comment by vepanimas** [comment]
It's hard to say exactly when it was fixed, but it works in the latest releases.
