### ISSUE TITLE
Prisma Schema Language Support

### ISSUE THREAD

**Issue by austincollinpena** [JetBrains/js-graphql-intellij-plugin#329]
I would love to have support for the new Prisma Schema Language. Is this something within the scope of this plugin, or is this something that should be made somewhere else? Or am I missing a way to do this?

[Link to PSL](https://github.com/prisma/specs/tree/master/schema)

Related Issue from Prisma V1:
[Old .prisma method ](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/144)

## Version and Environment Details
__Operation system__: Pop!_OS 19.10

__IDE name and version__:  Webstorm 2020.1

__Plugin version__: 2.4.0

**Comment by jimkyndemeyer** [comment]
Hi Austin,

PSL appears to be its own language, meaning that the entire featureset for language tooling would have to be implemented (parser, formatter, completion, error highlighting, go to definition etc.). Although related to the GraphQL ecosystem, this puts it outside the scope of this plugin, unless someone wants to champion the efforts and do a PR (and maintain going forward).

I think you best bet is to use https://github.com/prisma/specs/tree/master/vscode-extension if VS Code is an option for you.

**Comment by austincollinpena** [comment]
Makes sense, thank you!

**Comment by vepanimas** [comment]
Hey, I just made a plugin for Prisma which is available in the recent IntelliJ release (2022.3). You can download it here: https://plugins.jetbrains.com/plugin/20686-prisma-orm. So, closing this as fixed.
