### ISSUE TITLE
Support graphql.config.js

### ISSUE THREAD

**Issue by vjpr** [JetBrains/js-graphql-intellij-plugin#396]
I want to share my config between projects. Can we support the JS config format?

**Comment by vepanimas** [comment]
@vjpr hi! The current plugin version uses [legacy config format](https://github.com/kamilkisiela/graphql-config/tree/legacy#graphql-config). We have an issue (https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/296) to migrate to the most [recent](https://graphql-config.com/introduction) v3 version, which supports .js config format. I think it's one of the top priorities in the next releases.
