### ISSUE TITLE
Feature request: Support the DGS Framework

### ISSUE THREAD

**Issue by paulbakker** [JetBrains/js-graphql-intellij-plugin#442]
Netflix open sourced their [DGS Framework](https://github.com/Netflix/dgs-framework) earlier this year (I'm one of the maintainers). 
Because the `js-graphql-intellij-plugin` is pretty much the de-facto standard GraphQL for Intellij, it would be really great if we can support the DGS Framework in the plugin.

Features I have in mind:
* Scan `META-INF/schema/*` files for schemas embedded in JAR files. We use that for libraries containing shared types.
* Navigation from/to schema definitions from/to `@DgsData` methods (datafetchers) in Java/Kotlin sources.

If you're open to the idea of this sort of integration, we would be happy to contribute as well.

**Comment by vepanimas** [comment]
Oh, I missed this ticket, just at this time I was on a long vacation 😞. Looks like you've already addressed the first item in the list. We also could fix the second one, it's a matter of implementation several reference contributors (https://plugins.jetbrains.com/docs/intellij/reference-contributor.html#define-a-reference-contributor). Also, we now have a page that shows all the existing open-source implementations of the platform extension points. This link shows all known `referenceContributor` implementations https://plugins.jetbrains.com/intellij-platform-explorer?extensions=com.intellij.psi.referenceContributor.

I'm not very familiar with the Java plugin codebase, but there may already be some extensions that simplify the creation of annotation references, it looks like a frequently encountered task.

**Comment by vepanimas** [comment]
That's an interesting question. At first, I thought about suggesting adding it to this repo, but it could possibly impose some constraints on you. For example, you want to add a custom index for some reason, in that case all the clients of this plugin will use it even if they don't need it at all. Indexes shouldn't depend on the project, so you can't simply check a project setting and skip it. Also in the case of a separate plugin, you won't depend on our release cycle, which is quite unpredictable to be honest 😄.

But you obviously still will need to make the changes in the existing codebase to provide additional extension points in different places. I'm also interested in that to be able to support some graphql frameworks in the near future and don't hardcode them into the core. For example, we now have a custom extension to the GraphQL language (called GraphQL Endpoints Language) in the same repo, and I'm going to separate it completely using the same approach by adding the new extension points. Its extensions are already moved to a separate [plugin.xml](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/blob/master/resources/META-INF/graphql-endpoint.xml). Also we have some extension points which are implemented in the framework specific code in the `com.intellij.lang.jsgraphql.frameworks` package: https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/blob/master/resources/META-INF/plugin.xml#L38-L43

So, I think it would be better to implement most of the framework-specific features in a separate plugin while adding a new extension points into that plugin.
