### ISSUE TITLE
Config not working, no endpoints

### ISSUE THREAD

**Issue by Freaksed** [JetBrains/js-graphql-intellij-plugin#487]
I have a graphqlconfig set up, but it still says there are no endpoints available
![image](https://user-images.githubusercontent.com/1610638/129785990-b732468e-8188-43d0-876a-5c98d0b767aa.png)

**Comment by vepanimas** [comment]
Hi! Please, check if this one is your case https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/482?

**Comment by Freaksed** [comment]
I checked the fix for that issue, and it already had the file types associated

**Comment by vepanimas** [comment]
Could you please share your .graphqlconfig then?

**Comment by vepanimas** [comment]
Close as not reproduced
