### ISSUE TITLE
Allow deprecation of input values (field args, directive args, input fields)

### ISSUE THREAD

**Issue by honza-zidek** [JetBrains/js-graphql-intellij-plugin#507]
**Describe the bug**
An unexpected error message "... tried to use a directive 'deprecated' in the 'INPUT_FIELD_DEFINITION' location but that is illegal"

**To Reproduce**
1. In IntelliJ, create a *.graphqls file
2. Type
```graphqls
input MyData {
    name: String
    surname: String
    familyName: String @deprecated
    city: String
}
```
3. You get an error on the line `familyName`: "'familyName' tried to use a directive 'deprecated' in the 'INPUT_FIELD_DEFINITION' location but that is illegal"

**Expected behavior**
I don't think that @deprecated is illegal there - please explain or fix.

**Screenshots**
![image](https://user-images.githubusercontent.com/5145994/143455445-b3c75af6-3793-4f87-9d92-0847c6767724.png)

**Version and Environment Details**
IntelliJ IDEA 2021.2.3 (Ultimate Edition)
Build #IU-212.5457.46, built on October 12, 2021
Runtime version: 11.0.12+7-b1504.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
Non-Bundled Plugins: com.intellij.lang.jsgraphql (3.0.0), com.haulmont.jpab (5.8-212)

**Comment by vepanimas** [comment]
Hi @honza-zidek! Thank you for the report. This RFC https://github.com/graphql/graphql-spec/pull/805 is in-progress, in the latest published draft spec https://spec.graphql.org/draft/#sec--deprecated is still defined as
```
directive @deprecated(
  reason: String = "No longer supported"
) on FIELD_DEFINITION | ENUM_VALUE
```

What GraphQL implementation do you use on the server-side, does it already support this?

**Comment by honza-zidek** [comment]
@vepanimas: as for the GraphQL implementation:
```
<dependency>
	<groupId>com.graphql-java-kickstart</groupId>
	<artifactId>graphql-spring-boot-starter</artifactId>
	<version>11.0.0</version>
</dependency>

<dependency>
	<groupId>com.graphql-java-kickstart</groupId>
	<artifactId>graphql-webclient-spring-boot-starter</artifactId>
	<version>1.0.0</version>
</dependency>

<plugin>
	<groupId>io.github.kobylynskyi</groupId>
	<artifactId>graphql-codegen-maven-plugin</artifactId>
	<version>5.1.0</version>
</plugin>
````

- and yes, it does support the `@deprecated` directive on fields.

**Comment by honza-zidek** [comment]
@vepanimas 
> ... in the latest published draft spec https://spec.graphql.org/draft/#sec--deprecated is still defined as
> ```
> directive @deprecated(
>   reason: String = "No longer supported"
> ) on FIELD_DEFINITION | ENUM_VALUE
> ```
> 

What do you mean by "still defined"? I think it is just "defined" :) The text `"No longer supported" ` just explains why something is deprecated, not that the feature is not supported :)

**Comment by vepanimas** [comment]
@honza-zidek in the left part of the mentioned PR, you can see how it was defined earlier ("still" defined in the current draft specification, because it hasn't been merged yet), in the right part - how it will be defined in the future.
<img width="1738" alt="rfc" src="https://user-images.githubusercontent.com/10243762/143476974-5a557295-31f7-475c-82e5-c0b86ce86e17.png">

Also, `INPUT_FIELD_DEFINITION` has no relation to `FIELD_DEFINITION`, it can't be treated as a "subset". This is one of the reasons why this RFC exists at all, and you couldn't use a deprecation directive on the input field before.

**Comment by vepanimas** [comment]
https://github.com/graphql-java/graphql-java/pull/2186

**Comment by ndwhelan** [comment]
I've just ran into this issue. Would y'all be receptive to a PR?

**Comment by FreekVanDooren** [comment]
> I've just ran into this issue. Would y'all be receptive to a PR?

Me too. I've never tried to do anything with plugins, so not sure how to test any changes... Would there be more involved in this than changing https://github.com/JetBrains/js-graphql-intellij-plugin/blob/master/resources/definitions/Specification.graphql#L60 to
```
directive @deprecated(reason: String = "No longer supported") on FIELD_DEFINITION | ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION | ENUM_VALUE
```
?

**Comment by ndwhelan** [comment]
I don't think so, but I also have no experience building IntelliJ plugins.
I guess I can deal with a red squiggly line... Not sure JetBrains is very
invested in this plug-in.

**Comment by FreekVanDooren** [comment]
> Not sure JetBrains is very invested in this plug-in.

Don't know about that @vepanimas responded pretty quickly back in November.

> I guess I can deal with a red squiggly line... 

Red squiggly lines are haunting me in my dreams... 😥
