### ISSUE TITLE
Indication when using deprecated field in query

### ISSUE THREAD

**Issue by alonp99** [JetBrains/js-graphql-intellij-plugin#55]
Thanks for the great work Jim,

It will be great to have indication while writing a query if there`s use of deprecated fields.

**Comment by xamgore** [comment]
The most significant advantage of GraphQL is its ability to gradually update the schema, so there are no sudden changes. However, if such changes are unavoidable, you can ensure a smooth transition. Mark a field, argument, or function as deprecated, and the entire tooling will alert that migration is required. After migration, cut it in a month or two.

How frontend developers should see the deprecated fields:

![](https://raw.githubusercontent.com/apollographql/vscode-graphql/main/images/marketplace/warnings-and-errors.gif)

**Comment by vepanimas** [comment]
Is supported since 2024.1 https://youtrack.jetbrains.com/issue/WEB-63597/GraphQL-mark-deprecated-items-as-strikethrough-text.

**Comment by xamgore** [comment]
@vepanimas, thank you! <3
