### ISSUE TITLE
Unknown fieldPolicy/typePolicy directive of ApolloGraphql

### ISSUE THREAD

**Issue by Nailik** [JetBrains/js-graphql-intellij-plugin#597]
When i Try to use `@fieldPolicy` or `@typePolicy` to set [declarative cache IDs](https://www.apollographql.com/docs/kotlin/caching/declarative-ids/) i get Schema errors like 
`'Query' tried to use an undeclared directive 'fieldPolicy'` .

`extra.graphqls` looks like:

```
extend type Query @fieldPolicy(forField: "launch", keyArgs: "id")
extend type Launch @typePolicy(keyFields: "id")
```

**Comment by vepanimas** [comment]
From now on you can try to enable built-in type declarations for Apollo:

![image](https://user-images.githubusercontent.com/10243762/179379169-c54f7cda-a905-4b26-ac9c-e4548b32fa37.png)
