### ISSUE TITLE
Enable environment variables

### ISSUE THREAD

**Issue by llehn** [JetBrains/js-graphql-intellij-plugin#602]
At the moment there seems to be no way to make the plugin use the value of environment variable, other than explicitly giving it via the "Enter missing variable..." dialog.

This basically turns the advertised functionality of using something like ${env:TOKEN} into something like
${SHOW_PROMPT} (or SHOW_PROMPT_1, SHOW_PROMPT_2, to support different values) 

I saw the discussions about supporting env files, which IMHO totally have the wrong point - the concern which env files in which order should be applies is one which is not what this plugin is about.

I hope somebody corrects me and i'm just too stupid for not being able to find a way to use the enviroment variable (the thing that System.getenv() gets the value for)

**Comment by llehn** [comment]
They are set of course.

**Comment by vepanimas** [comment]
@llehn I fixed that, now env variables should be available.
