### ISSUE TITLE
Wrong highlighting color for the field named type

### ISSUE THREAD

**Issue by mostafa-rz** [JetBrains/js-graphql-intellij-plugin#610]
Hi, after the recent updating of the plugin in phpstorm the `type` field name is highlighted wrong. The plugin version is 3.1.4.

![Screenshot 2022-06-13 093003](https://user-images.githubusercontent.com/71334549/173302115-37425bbe-d271-4550-ad6d-35129d9d277a.png)

**Comment by vepanimas** [comment]
@mostafa-rz hi! What color scheme do you use?

**Comment by mostafa-rz** [comment]
@vepanimas [Dracula](https://plugins.jetbrains.com/plugin/12275-dracula-theme)
