### ISSUE TITLE
@nonnull directive not recognized in query file

### ISSUE THREAD

**Issue by adamoBMX** [JetBrains/js-graphql-intellij-plugin#611]
**Describe the bug**
The plugin does not seem to recognize the `@nonnull` field directive in Android Studio.

**To Reproduce**
1. Open a `.graphql` file in Android Studio
2. Write a query
3. After a field, type `@nonnull`.

**Expected behavior**
1. `nonnull` would show up in the directive auto-complete list
2. `@nonnull` would not be marked red and labelled as an unknown directive

**Screenshots**
<img width="131" alt="Screen Shot 2022-06-14 at 22 41 41" src="https://user-images.githubusercontent.com/82281541/173619304-f57b2003-4a17-4e8f-a43b-ff580bb40f3d.png">

<img width="371" alt="Screen Shot 2022-06-14 at 22 40 39" src="https://user-images.githubusercontent.com/82281541/173619097-011f6293-172f-4ef4-9aeb-fb08538876f6.png">
lem.

**Version and Environment Details**
Operation system: macOS 12.4
IDE name and version: Android Studio Chipmunk | 2021.2.1 Patch 1
Plugin version: 3.1.4

**Additional context**
Not a big deal, still seems to compile okay

**Comment by vepanimas** [comment]
Hello @adamoBMX! `@nonnull` is not a standard directive AFAIK, so what GraphQL framework do you use? For example, this directive is provided in apollo-kotlin, and you can try to enable type definitions for that framework on the plugin settings page.

![Preferences 2022-07-15 18-15-44](https://user-images.githubusercontent.com/10243762/179254109-013808be-7184-4163-9ebb-d45be8130e89.png)

**Comment by adamoBMX** [comment]
Ah yes, that's exactly the setting I was missing! Thanks for explaining, much appreciated. 🙂
