### ISSUE TITLE
It is possible to use an endpoint for schema in .graphqlconfig?

### ISSUE THREAD

**Issue by ThStock** [JetBrains/js-graphql-intellij-plugin#612]
I tried `"schemaPath": "http://localhost:8080/schema.graphql",` without success.

Can you help me?

```json
{
  "name": "Untitled GraphQL Schema",
  "schemaPath": "http://localhost:8080/schema.graphql",
  "extensions": {
    "endpoints": {
      "Default GraphQL Endpoint": {
        "url": "http://localhost:8080/graphql",
        "headers": {
          "user-agent": "JS GraphQL"
        },
        "introspect": false
      }
    }
  }
}

**Comment by jimkyndemeyer** [comment]
There's an example of doing introspection at https://blog.jetbrains.com/webstorm/2019/04/featured-plugin-js-graphql/#doing_introspection

The `schemaPath` is used to point to a file on local disk into which the result of introspecting your GraphQL endpoint is written.
