### ISSUE TITLE
Schema request timeout

### ISSUE THREAD

**Issue by jaydensmith** [JetBrains/js-graphql-intellij-plugin#613]
It takes a few seconds to download my schema, the new version (3.2.0) throws a timeout error.

**Comment by vepanimas** [comment]
Hello @jaydensmith, I fixed it and the release is already available on Github. It could take several days to approve a new plugin upload in the Marketplace, so you can install an update manually if you want from the release page.

https://github.com/JetBrains/js-graphql-intellij-plugin/releases/tag/3.2.1

**Comment by VladimirAndrianov96** [comment]
Hey!

I'm facing the same issue too, but the timeout from my CMS solution is much longer, as the retrospection query returns around 15k+ lines of code, is there any way to extend the timeout manually for the plugin in WebStorm?

**Comment by vepanimas** [comment]
Please, check the new 3.2.1 updated version, it's already available in the marketplace. The default timeout is 15 seconds now, but if it's still not enough, it would be possible to configure a timeout using a registry key.

**Comment by VladimirAndrianov96** [comment]
Here is the workaround for this issue, thanks, it worked for me!

The registry key can be updated like that:

```
Press Ctrl-Alt-Shift-/ and select "Registry" from the menu that appears.
(If that keyboard shortcut is not working for you, use your configured keyboard shortcut for Find Action. On Mac by default it is Shift+⌘+A, on Windows it is Shift+Ctrl+A ([docs](https://blog.jetbrains.com/idea/2020/03/top-15-intellij-idea-shortcuts/)). Then type "Registry" and click or hit enter.)
```

<img width="883" alt="image" src="https://user-images.githubusercontent.com/15718242/181217813-23cd8ff0-1635-47f7-8428-3a3601d34f5e.png">

<img width="890" alt="image" src="https://user-images.githubusercontent.com/15718242/181217954-0d934f81-e765-43e5-a60c-6bfbc5ab00b4.png">
