### ISSUE TITLE
Option to use .graphqls from external libraries

### ISSUE THREAD

**Issue by bramklg** [JetBrains/js-graphql-intellij-plugin#624]
I'm using an external library in my project that has a `.graphqls` file where some directives are defined. I would like to tell the plugin that it also needs to scan/use the files from that library so I have proper autocompletion and documentation.

As far as I know, this isn't possible yet, am I right or did I overlook something in the documentation?

**Comment by samjcombs** [comment]
+1 to this.  Specifically I'd like to include .graphqls files in a java dependency.  I tried configuring .graphqlconfig a few different ways to no avail.  This would be a great feature.

**Comment by samjcombs** [comment]
^^^ bump, any movement on this one?  I'm thinking of forking this functionality...

**Comment by vepanimas** [comment]
Hi! I've reworked the configuration in the last update to match modern GraphQL configuration approaches. This means that we can finally start thinking about extending it to meet more specific needs. Do you have a proposal for how we should configure which libraries to include? I thought about that and see some possible problems along the road, but maybe we can find a good enough solution together. 

For instance, the most challenging scenario is a multi-project setup that includes multiple libraries, some of which should be linked with project 1 and not project 2.

**Comment by alexeyzimarev** [comment]
@vepanimas it seems like something got broken in the config discovery with the new release.
I get this message:
<img width="358" alt="image" src="https://user-images.githubusercontent.com/2821205/233837281-84bebc4b-d01b-416b-8fcd-57959a8d03e4.png">
and the file is right there:
<img width="289" alt="image" src="https://user-images.githubusercontent.com/2821205/233837324-ea4ab87a-f54a-4206-a350-b9b06d73c35d.png">

It definitely worked fine just last week. Sorry for hijacking the issue, it seems to be related to configs.

**Comment by vepanimas** [comment]
@alexeyzimarev hi, it's definitely not related to that issue. Do you use Rider? If so, please, try https://github.com/JetBrains/js-graphql-intellij-plugin/issues/647#issuecomment-1446197174. A possibly related issue https://github.com/JetBrains/js-graphql-intellij-plugin/issues/659.

**Comment by bramklg** [comment]
Any update on this? Is 'my' problem going to be solved some day or is this just something I have to work around/deal with?

**Comment by vepanimas** [comment]
@bramklg hi! I finally started working on that. Could you please provide a more detailed description of the project's structure? I'm particularly interested in understanding the layout of the library where the GraphQL files are stored. Probably, it looks something like that on the screenshot? it would be even better if you could provide library artifact ID for testing purposes if it's open-source.

![image](https://github.com/JetBrains/js-graphql-intellij-plugin/assets/10243762/a8af7acb-200f-4fa1-aec6-3b5ba67a81fc)

**Comment by vepanimas** [comment]
[Fixed](https://youtrack.jetbrains.com/issue/WEB-64193/GraphQL-locate-schemas-in-java-libraries), should be available in the next 2024.1 EAP. Please feel free to reach out if you have any questions or feedback.

**Comment by bramklg** [comment]
Hi @vepanimas. Tnx for implementing this! I forgot to answer your question but the structure looks indeed a bit like your screenshot. We have internal shared libraries containing `.graphqls` files used in other projects. If you still need a sample project lmk.

**Comment by BoD** [comment]
Hey @vepanimas sorry I'm late to the party - I'm trying out this feature, and while it works for me when not providing a `graphql.config.yml` file, it doesn't when I do.

From [the ticket](https://youtrack.jetbrains.com/issue/WEB-64193/GraphQL-locate-schemas-in-java-libraries) description I seem to understand that it still should work if the config file is located in the module that has the dependency containing the graphql definitions.

In my case I only have one module (root).

I have this simple project that shows the issue:
- https://github.com/BoD/apollo-kotlin-template/tree/definitions-in-jar
- checkout the `definitions-in-jar` branch
- open the project
- in `schema.graphqls`, `@MyDirective` is resolved ✅
- rename `XXXgraphql.config.yml` to `graphql.config.yml`
- `@MyDirective` is no longer resolved ❌ 

Thanks!

**Comment by vepanimas** [comment]
@BoD The issue in your case is that you have more than one module, which confused me at first as well. If you look at the screenshot, you'll see that the dependencies from the build script are in the `main` module, not in the root `apollo-kotlin-template-lib-scope`. When you move the GraphQL config to the main module, as I did in the screenshot, everything works as expected. I should say that I'm not fully confident in how it should behave in this scenario, as I don't have much experience with the Java subsystem in IntelliJ IDEA and its project model.

![image](https://github.com/user-attachments/assets/3e174e3e-178e-400d-9d5f-de3f5b83948a)
