### ISSUE TITLE
ID scalar type

### ISSUE THREAD

**Issue by glebsts** [JetBrains/js-graphql-intellij-plugin#634]
Hi there,
First of all, thank you for great products!

I was composing a graphql payload for my tests having field of `ID`  type, and when I Ctrl+clicked this type it brought me to [plugin docs](https://github.com/JetBrains/js-graphql-intellij-plugin/blob/master/resources/definitions/Specification.graphql#L12) saying:

> When expected as an input type, any string (such as "4") or integer (such as 4) input value will be accepted as an ID

So I bravely left `4` as my ID field. It broke on deserialization during test run, saying string was expected (using `gengql` for Go), so I went to graphql.org for truth and found [there](https://graphql.org/learn/schema/):

> ID: The ID scalar type represents a unique identifier, often used to refetch an object or as the key for a cache. The ID type is serialized in the same way as a String; however, defining it as an ID signifies that it is not intended to be human‐readable.

Suggestion: improve docs removing mention of integer as a good value for standard `ID` scalar type.

**Comment by vepanimas** [comment]
Hi, @glebsts. You can definitely specify an integer for the [ID](https://spec.graphql.org/October2021/#sec-ID) scalar type, your case should be related to the specific graphql implementation used, e.g. `gengql`.

> [Input Coercion](https://spec.graphql.org/October2021/#sec-ID.Input-Coercion)
When expected as an input type, any string (such as "4") or integer (such as 4 or -4) input value should be coerced to ID as appropriate for the ID formats a given GraphQL service expects. Any other input value, including float input values (such as 4.0), must raise a request error indicating an incorrect type.
