### ISSUE TITLE
Plugin not compatible with IJ 2023.1 EAP

### ISSUE THREAD

**Issue by lwasyl** [JetBrains/js-graphql-intellij-plugin#640]
Would it be possible to publish the plugin compatible with 
```
IntelliJ IDEA 2023.1 EAP (Ultimate Edition)
Build #IU-231.5920.14, built on January 27, 2023
```
?

**Comment by falkenhawk** [comment]
v3.3.1 is listed in the changelog https://github.com/JetBrains/js-graphql-intellij-plugin/blob/master/CHANGELOG.md#331---2022-11-23
but for some reason it was never published to the marketplace https://plugins.jetbrains.com/plugin/8097-graphql

**Comment by vepanimas** [comment]
It should be available in the marketplace now 🎉.
