### ISSUE TITLE
Wrong year in changelog

### ISSUE THREAD

**Issue by bosycom** [JetBrains/js-graphql-intellij-plugin#643]
https://github.com/JetBrains/js-graphql-intellij-plugin/blob/master/CHANGELOG.md

is: [3.4.0] - 2022-02-07
should be: [3.4.0] - 2023-02-07

Not sure if it's worth mentioning, but I thought I'd let you know :)

**Comment by bosycom** [comment]
Just saw, there is already a pull request. So I close it.

**Comment by vepanimas** [comment]
Hi, thank you for the info! I just merged a PR. It shouldn't affect anything, just misleading a bit.
