### ISSUE TITLE
v4 not picking up local json schema file

### ISSUE THREAD

**Issue by arturkin** [JetBrains/js-graphql-intellij-plugin#655]
**Describe the bug**
Hey, thanks for all the hard work, this plugin is really awesome!
Plugin just updated for me to v4, and I'm not able to use it anymore - not picking up any types. I've updated config file to the use new structure

**To Reproduce**
v3 working config
**`.graphqlconfig`**
```
{
  "schemaPath": "../graphql-schema.json",
  "documents": "src/**/*.graphql",
}
```

v4 config (non working)
**`graphql.config.yml`**
```
schema: ../graphql-schema.json
documents: 'src/**/*.graphql'
```

Was the json schema support dropped? I can see mostly `.graphql` examples in docs now.

**Comment by vepanimas** [comment]
@arturkin hi! Can you try moving `graphql-schema.json` to the directory where the config file is located? This might solve the problem. JSON schemas should work, but they work differently now, maybe it's an issue with paths.
```
schema: ./graphql-schema.json
documents: 'src/**/*.graphql'
```

**Comment by arturkin** [comment]
Yes! that worked, thank you!
