### ISSUE TITLE
Query variables editor is not visible in 2023.1

### ISSUE THREAD

**Issue by vepanimas** [JetBrains/js-graphql-intellij-plugin#658]
Query variables editor is not visible in 2023.1.

Reported here https://github.com/JetBrains/js-graphql-intellij-plugin/issues/83#issuecomment-1517876453.

**Comment by lorthirk** [comment]
It seems the panel appears but does not expand. If you look closely, after clicking the V shows a fraction of a blinking cursor just below it, and it moves when typing on the keyboard, but you can't see what you write in. I honestly think this is a major issue, hoping for a quick release of a fix.

**Comment by vepanimas** [comment]
@lorthirk I just released a new version and uploaded plugin builds to the marketplace, they will be available after approval in several days. If you want you can install a plugin manually from the [release page](https://github.com/JetBrains/js-graphql-intellij-plugin/releases/tag/4.0.1), just make sure to use the correct version: `4.0.1-222` is for 2022.2-2022.3, and `4.0.1` is for 2023+.

**Comment by olof-nord** [comment]
People involved in this project, thank you! Just upgraded to 4.0.1 and the variables editor is looking glorious 🥇
