### ISSUE TITLE
Schema reuse ver 4

### ISSUE THREAD

**Issue by andrzejbl** [JetBrains/js-graphql-intellij-plugin#661]
Hi, 

in the previous version, I've been reusing graphql files across many projects. 
for example, I used 
`libs/pricing/schema.graphql`

in many other schemas. 
It worked very well so far. After upgrading to v4, projects defined after the project using one file are not seeing this file again. 
I'm using a single config file for the whole project.

Is this a bug or there was an intentional change?

**Comment by vepanimas** [comment]
@andrzejbl Hi! To be honest, I didn't think about that scenario and haven't tested it for that case 😞. I've implemented the config matching as closely as possible to the https://github.com/kamilkisiela/graphql-config library. Therefore, I need some time to figure out how it works there. 

You can try to downgrade a plugin to a 3.4.0 version as a temporary solution, sorry for the inconvenience.

It would be great if you could share the config file you use, of course without any endpoints, credentials, or other sensitive data.

**Comment by andrzejbl** [comment]
Here is an example of my config for older version:

`
   "PhotographerServer": {
      "includes": [
        "./graphql/apps/photographer/src/**/*.graphql",
        "./graphql/libs/organization-offer/**.graphql",
        "./graphql/libs/organization-offer-front/**.graphql",
        "./graphql/libs/upload/*.graphql",
        "./graphql/schema/common.graphql"
       .....
      ]
    },
    "PhotographerClient": {
      "includes": [
        "./projects/photographer-panel/src/app/queries.graphql", <-- frontend queries
        "./graphql/apps/photographer/src/**/*.graphql",
        "./graphql/libs/organization-offer/*.graphql",
        "./graphql/libs/organization-offer-front/*.graphql",
        "./graphql/libs/upload/*.graphql",
        "./graphql/schema/common.graphql"
          ...
      ]
    }
`

Downgrane solved the problem temporarily. Let me know if I can be of any help.

**Comment by vepanimas** [comment]
@andrzejbl What IDE version do you use? I think I fixed it but it would be great if you could try it before the release.

**Comment by andrzejbl** [comment]
Webstorm: Build #WS-231.8109.174, built on March 28, 2023

**Comment by vepanimas** [comment]
@andrzejbl Could you please try this recent build including a fix? Does it work for your project setup?

[js-graphql-intellij-plugin-4.0.0.zip](https://github.com/JetBrains/js-graphql-intellij-plugin/files/11333834/js-graphql-intellij-plugin-4.0.0.zip)

**Comment by reckter** [comment]
@vepanimas When can we expect the fix to land in the release version?

**Comment by vepanimas** [comment]
@reckter We'll release it by the end of the week, we’re testing the build at the moment🤞.
