### ISSUE TITLE
Autocompletion doesn't work inside GraphQL arguments after 4.0.0

### ISSUE THREAD

**Issue by arlampin** [JetBrains/js-graphql-intellij-plugin#662]
**Describe the bug**
Autocompletion doesn't show anything for argument values. The top level argument names are suggested, but values are not in any way. This includes enum values (see screenshots) as well as anything inside any nested argument object. So for example if there an object argument, that argument's content is not autocompleted at any level.

**Screenshots**
![Screenshot 2023-04-26 at 11 43 42](https://user-images.githubusercontent.com/1737104/234522554-28de5f44-44be-4378-a671-5dce6d320bf4.png)
![Screenshot 2023-04-26 at 11 43 49](https://user-images.githubusercontent.com/1737104/234522559-6be6faac-b4f7-4157-9f2b-7a665c4d20f2.png)

**Version and Environment Details**
Operation system: Macos 13
IDE name and version: IntelliJ IDEA 2023.1 (Ultimate Edition)
Plugin version: 4.0.0

**Comment by arlampin** [comment]
Kind of. It seems to work with .graphql files as you said, but it doesn't work with any embedded GraphQL queries. For example queries embedded in .tsx files using `gql` tag.

**Comment by vepanimas** [comment]
> it doesn't work with any embedded GraphQL queries

Thank you for mentioning that. I'll check it out as well 👍.
