### ISSUE TITLE
Cannot run my queries when I extend the root Query type.

### ISSUE THREAD

**Issue by nanafan93** [JetBrains/js-graphql-intellij-plugin#671]
My project structure is as shown below.  Basically I want to start off with an empty schema and then "fill in" the types and extend the operations from all other files. I would prefer to not change my structure. 

/graphql

- common
  - schema.graphqls
- folder1
  - A.graphqls // type definitions query mutation extensions
  - B.graphql  // type definitions query mutation extensions
- folder2
  - C.graphqls  // type definitions query mutation extensions
  - D.graphqls   // type definitions query mutation extensions

The schema.graphqls file is defined as 

```
scalar GraphQLVoid
scalar GraphQLLong

schema {
    query: Query
}

type Query {
}

type Mutation {
}
```
and then in each of the files in the directories I extend the query/mutation field arbitrarily and define new types as well. For example 

A.graphls would be something like 

```
type Blah {
a:String!
b: Int!
}

extend type Query {
hello: Blah!
}
```

My problem is whenever I place the caret on any of these "extended" query definitions, it refuses to execute the query. Also, it tries to query starting from the top of the file resulting in errors like. 

Validation error of type NonExecutableDefinition: The Blah definition is not executable.
Validation error of type NonExecutableDefinition: The Query definition is not executable.

How do I get around this ?

**Comment by vepanimas** [comment]
Hi! AFAIU you're trying to execute a type definition, instead of a query, it doesn't work that way.

That would be a proper query for your schema:
```
query MyQuery {
  hello {
    a
    b
  }
}
```

**Comment by vepanimas** [comment]
`Validation error of type NonExecutableDefinition: The Blah definition is not executable.
Validation error of type NonExecutableDefinition: The Query definition is not executable.` these errors mean that you put a caret on a type definition and ran an action to execute a query. That doesn't work in GraphQL.

What you mentioned here is not a "query", it's a type definition, you can't send it to the server. Or maybe I don't understand your question 🤷‍♂️ 
```
type Blah {
a:String!
b: Int!
}

extend type Query {
hello: Blah!
}
```

**Comment by vepanimas** [comment]
You can put a caret right into the query in the editor, select an endpoint in the toolbar above, and press on the green arrow button or `ctrl + enter`.

![image](https://github.com/JetBrains/js-graphql-intellij-plugin/assets/10243762/d82d893a-72d4-48c7-b406-b99e59d10c62)
