### ISSUE TITLE
3.4.0 -> v4 (Breaking changes were introduced)

### ISSUE THREAD

**Issue by stephenjason89** [JetBrains/js-graphql-intellij-plugin#672]
**Before you create the issue**
- If you're using an EAP, try with a stable version. If that works, please mention it in the issue along with both versions
- Please search the [existing issues](https://github.com/JetBrains/js-graphql-intellij-plugin/issues?q=sort%3Aupdated-desc) before opening a new issue
- Review the [developer guide](https://github.com/JetBrains/js-graphql-intellij-plugin#developer-guide)

**Describe the bug**
Breaking change introduced with v4

**To Reproduce**
This is how it looks like after upgrading to 4
<img width="1078" alt="image" src="https://github.com/JetBrains/js-graphql-intellij-plugin/assets/3810177/d243cf71-37e2-4cd2-b4c3-e5ce3fae06a9">

.graphqlconfig
<img width="612" alt="image" src="https://github.com/JetBrains/js-graphql-intellij-plugin/assets/3810177/af244e20-0557-4c9d-a0ac-dd4f1984d01e">

**Expected behavior**
version 3.4 everything is working fine
<img width="774" alt="image" src="https://github.com/JetBrains/js-graphql-intellij-plugin/assets/3810177/172b84b6-7916-467c-9165-fec8c6e0cee5">

**Version and Environment Details**
Operation system: mac os ventura
IDE name and version: intellij idea 2022.3.2
Plugin version: 4 onwards

**Additional context**
Rolling back to 3.4 fixes everything

**Comment by efstathiosntonas** [comment]
Had the same issue, it fixes it self automatically after switching to .yml config file

**Comment by stephenjason89** [comment]
@vepanimas I just tried your solution and it worked perfectly.
Sorry for the very late reply as I might have overlooked this issue.


Again, thank you so much!
