### ISSUE TITLE
Unknown field , android , multi modules

### ISSUE THREAD

**Issue by Isma3ilMohamed** [JetBrains/js-graphql-intellij-plugin#680]
hey everyone 

I'm working on multi module project and have a module for schema

and feature modules for different feature in a project

so while typing any query, mutation or use fragment from schema module
it shows me this error

```
Unknown field "": The parent selection or operation does not resolve to a valid schema type
```
project build successfully and queries, mutation also generated 
but file show error on whole stuff and this one for example

![image](https://github.com/JetBrains/js-graphql-intellij-plugin/assets/34917869/4ab02b37-a6b5-4e35-a625-f6021c814898)

so i want to know how to fix that in order to could use autocomplete 

my android studio version `Android Studio Giraffe | 2022.3.1`

and the plugin version `4.0.1-222`

thanks for all

**Comment by amrkamal123** [comment]
same i have the same error !!!

**Comment by vepanimas** [comment]
@Isma3ilMohamed hi! Do you have any kind of graphql configuration in the project? And could you describe your project structure? Also, are there any graphql errors in the GraphQL tool window?

**Comment by Isma3ilMohamed** [comment]
yes @vepanimas 
it's exactly like that 
```
root
    module1
          schema.graphql
          graphql.config.yml
          Fragments.graphql
     module2
          someQuery.graphql
     module3
          someQuery.graqhql
          someMutations.graphql

     ....etc
```

**Comment by vepanimas** [comment]
@Isma3ilMohamed is it possible to move the config to the root and change the corresponding paths inside of it? Because the plugin can't actually find a schema for module2 and module3. In the previous releases it worked, because the plugin just ignored a config in your case and worked globally for the whole project.

**Comment by Isma3ilMohamed** [comment]
hey @vepanimas 
sorry for being late 
and I made your recommended edits and it works 
make it like that
```
schema: PASS_TO_SCHEMA_IN_ITS_MODULE
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: https://example_url.com/graphql/
      headers:
        user-agent: JS GraphQL
      introspect: false

```
but I've another issue as you see i made a specific file for fragment and need to know
 if there is anyway 
to add fragments file path reference to the configuration file 
in order to be visible for other files in other modules
If not possible we could close this issue 
and thanks so much for your help

**Comment by vepanimas** [comment]
@Isma3ilMohamed I'm unsure if I understood a question correctly, but it looks like specifying the `documents` key including your fragments should help. Have you tried it? Something like that:
```
projects:
  frontend:
    schema: https://my.api.com/graphql
    documents: frontend/**/*.{graphql,js,ts}
    exclude: queries/** 
  backend:
    schema: backend/schema.graphql
    documents: backend/**/*.graphql
```

**Comment by Isma3ilMohamed** [comment]
yes that is working with me 👏 
thanks @vepanimas for your support
