### ISSUE TITLE
Third-Party Plugins Notice

### ISSUE THREAD

**Issue by flekmatik** [JetBrains/js-graphql-intellij-plugin#681]
**Describe the bug**
I am getting a warning message when installing this plugin. If this plugin is maintained by JetBrains this warning shouldn't be necessary right? I don't want to open any backdoor to my computer so I take such warnings quite seriously.

**To Reproduce**
1. Install this plugin in Webstorm

**Expected behavior**
No warning message because this plugin is maintained by JetBrains.

**Screenshots**
<img width="451" alt="image" src="https://github.com/JetBrains/js-graphql-intellij-plugin/assets/4591928/8fb8fb6f-a725-45df-90ca-ad197a7b8d9e">

**Version and Environment Details**
Operation system: MacOS
IDE name and version: Webstorm 2023.2
Plugin version: 4.0.2

**Additional context**
GraphQL seems to me like a quite common technology in web development and I'd expect it to be part of such IDE. It's strange to have to install it from "untrusted" sources. Even if it'd be a paid addon like datagrip addon.

**Comment by vepanimas** [comment]
Hi! The plugin was initially developed and maintained for a long time by @jimkyndemeyer, and he did a really great job! The plugin has become a standard for GraphQL support in the IntelliJ ecosystem. So, this notice is expected, and installing it won't cause any issues.

Now we gradually transition the plugin to the IntelliJ repository and adapt it to our build and release process. Several days ago I [changed](https://github.com/JetBrains/js-graphql-intellij-plugin/commit/76b884bb654b62f0f905647514b47ce1bb37cd9f#diff-6ce03e028ee0ab9572d21f9158240e43894b4f8d1ef8e678a0202dc89c8bf089R13) the vendor to JetBrains, so it won't show that warning in future releases.
