### ISSUE TITLE
The front end cannot recognize fields and types. Can it provide access to the remote gateway to obtain the scheme and provide code completion and checking functions?

### ISSUE THREAD

**Issue by tianlongJ** [JetBrains/js-graphql-intellij-plugin#688]
![image](https://github.com/JetBrains/js-graphql-intellij-plugin/assets/50390874/949a7932-dcce-459d-a7da-f6b0abad1995)

**Comment by mendrik** [comment]
I have local schema.graphql file which isn't picked up either.

**Comment by vepanimas** [comment]
Hi! Sorry, but there is not enough information to help you. Have you checked the docs https://github.com/JetBrains/js-graphql-intellij-plugin#configuration? To load a schema from the remote endpoint, you need to create a graphql config file and specify an endpoint there https://github.com/JetBrains/js-graphql-intellij-plugin#remote-schemas.

**Comment by tianlongJ** [comment]
> 你好！抱歉，没有足够的信息来帮助您。您是否 https://github.com/JetBrains/js-graphql-intellij-plugin#configuration 检查过文档？要从远程端点加载架构，您需要创建一个 graphql 配置文件并指定一个端点 https://github.com/JetBrains/js-graphql-intellij-plugin#remote-schemas。

I have configured it and can access remote documents and get code help.Thanks.
