### ISSUE TITLE
GraphQL Injections Break with TypeScript Type Assertions

### ISSUE THREAD

**Issue by brianlenz** [JetBrains/js-graphql-intellij-plugin#726]
**Describe the bug**
The GraphQL plugin doesn't seem to handle injections in TypeScript when the string's type is set to a specific type via type assertions (via the `as` operator).

**To Reproduce**
1. Define a string with the `/* GraphQL */` injection prefix.
2. Use a TypeScript type assertion to set the type of the string with the `as` keyword.

**Expected behavior**
The GraphQL plugin should still treat the string as GraphQL with Intellisense, Autocomplete, etc.

**Screenshots**
Here's a GraphQL query that works:

![Screenshot 2024-10-17 at 3 58 28 PM](https://github.com/user-attachments/assets/d091603c-c14e-4636-a9b9-4f75f3ebe9d6)

Here's the same GraphQL query with a type assertion that does _not_ work:
![Screenshot 2024-10-17 at 3 58 07 PM](https://github.com/user-attachments/assets/eac6bcc7-b626-478a-ae55-3bb2e19f9668)

**Version and Environment Details**
Operation system: macOS Sequoia `15.0.1`
IDE name and version: IntelliJ IDEA 2024.2.3 (Ultimate Edition), Build #IU-242.23339.11, built on September 24, 2024
Plugin version: `242.21829.3`

**Additional context**

**Comment by vepanimas** [comment]
Hi @brianlenz! Thank you for the report. I fixed it [WEB-69817](https://youtrack.jetbrains.com/issue/WEB-69817) and the fix should be available in the upcoming 2024.3 update.

**Comment by brianlenz** [comment]
Amazing, thank you, @vepanimas!
